library(sqldf)
library(lubridate)
dat <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007', '2/2/2007')", sep = ";")
png(file = "plot4.png")
par(mfcol = c(2,2))
plot(dmy_hms(paste(dat$Date, dat$Time)),dat$Global_active_power, xlab = "", ylab = "Global Active Power (killowatts)", type = "l")
plot(dmy_hms(paste(dat$Date, dat$Time)),dat$Sub_metering_1, col = "black", xlab = "", ylab = "Energy Sub Metering", type = "s")
points(dmy_hms(paste(dat$Date, dat$Time)),dat$Sub_metering_2, col = "red", xlab = "", ylab = "Energy Sub Metering", type = "s")
points(dmy_hms(paste(dat$Date, dat$Time)),dat$Sub_metering_3, col = "blue", xlab = "", ylab = "Energy Sub Metering", type = "s")
legend("topright", c("Sub_metering1", "Sub_metering2", "Sub_metering3"), col = c(1,2,4), lty = 1 )
plot(dmy_hms(paste(dat$Date, dat$Time)),dat$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(dmy_hms(paste(dat$Date, dat$Time)),dat$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "l")
dev.off()